### ISSUE TITLE
Additional resource(s) to add in the resource section of the presentation and book

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/workshop08#5]
- [x] GAMs in R by Noam Ross (https://noamross.github.io/gams-in-r-course/)
- [x] Pedersen EJ, Miller DL, Simpson GL, Ross N. 2019. Hierarchical generalized additive models in ecology: an introduction with mgcv. PeerJ 7:e6876 https://doi.org/10.7717/peerj.6876

**Comment by estebangongora** [comment]
- [x] Additionally, the references and citations in the book don't use the bookdown notation so they do not appear automatically in the References chapter. The .bib file needs to be updated so these citations show up properly.

**Comment by katherinehebert** [comment]
References are now in the .bib file here, and forced to show in the book. Also updated the resource list and corrected broken links in https://github.com/QCBSRworkshops/workshop08/commit/619c64dfb47bc4a4ce3aae189688143fea380eeb
