### ISSUE TITLE
Add packages to the book

### ISSUE THREAD

**Issue by estebangongora** [QCBSRworkshops/workshop08#7]
Not all the packages used in the workshop are included in the preparation section of the book. For example `gamm` and `gamm4` are mentioned multiple times in the GAMM section, but they are not included in the first chapters.

**Comment by katherinehebert** [comment]
Because gamm4 is mentioned but isn't used in the code, I did not add it to the package list, but did add a link to it on CRAN when it is mentioned. 

I also changed the phrasing to make this more clear, and mentioned the gamm() function within mgcv that is used throughout the GAMM section.
